services:
  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Set to true if you have a connection string set in .env:
      - APPLICATIONINSIGHTS_ENABLED=false
      # Enables B2C login/logout flow locally. Set additional configs in .env:
      - PETSTOREAPP_B2C_ENABLED=false
      # Enables Spring Security locally. Use together with B2C settings above:
      - PETSTORE_SECURITY_ENABLED=false

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    env_file:
      - .env

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    env_file:
      - .env

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    env_file:
      - .env