petstore:
  service:
    pet:
      url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
      reserver:
        url: ${ORDERITEMSRESERVER_URL:http://localhost:8084}
  security:
    # Enable this together with 'cloud.azure.active-directory.b2c.enabled = true' in Module 10
    enabled: ${PETSTORE_SECURITY_ENABLED:false}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
    applicationinsights:
      enabled: false
    security:
      enabled: false
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          enabled: ${PETSTOREAPP_B2C_ENABLED:false}
          base-uri: ${PERSTORE_B2C_BASE_URI}
          credential:
            client-id: ${PERSTORE_B2C_CLIENT_ID}
            client-secret: ${PERSTORE_B2C_SECRET}
          login-flow: sign-up-or-sign-in
          logout-success-url: ${PERSTORE_B2C_LOGOUT_URL}
          user-flows:
            sign-up-or-sign-in: ${PERSTORE_B2C_USERFLOW_SIGNUP_SIGNIN}
            password-reset: ${PERSTORE_B2C_USERFLOW_PASSWORD_RESET}
