petstore:
  service:
    pet:
      url: ${PETSTOREPETSERVICE_URL:http://localhost:8081}
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order:
      url: ${PETSTOREORDERSERVICE_URL:http://localhost:8083}
      reserver:
        url: ${ORDERITEMSRESERVER_URL:http://localhost:8084}
  security:
    # Enable this together with 'cloud.azure.active-directory.b2c.enabled = true' in Module 10
    enabled: ${PETSTORE_SECURITY_ENABLED:false}
server:
  port: ${PETSTOREAPP_SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
    applicationinsights:
      enabled: false
    security:
      enabled: false
spring:
  application:
    name: petstoreapp
  thymeleaf:
    cache: false
  cache:
    cache-names: currentUsers
  cloud:
    azure:
      active-directory:
        b2c:
          # Enable this together with 'petstore.service.security.enabled = true' in Module 10
          enabled: ${PETSTOREAPP_B2C_ENABLED:false}
          # Add base-uri, client-id, client-secret, login-flow, logout-success-url, and user-flows