name: Build and Deploy Selected Module

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Select the project to build and deploy'
        required: true
        type: choice
        options:
          - petstoreapp
          - petstoreorderservice
          - petstorepetservice
          - petstoreproductservice
          - all

jobs:
  detect-and-build:
    name: Build and Deploy Selected Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build and Push petstoreapp
        if: ${{ inputs.project == 'petstoreapp' || inputs.project == 'all' }}
        uses: ./.github/actions/build-and-push-module
        with:
          module-name: petstoreapp
          branch-name: ${{ github.ref_name }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstoreorderservice
        if: ${{ inputs.project == 'petstoreorderservice' || inputs.project == 'all' }}
        uses: ./.github/actions/build-and-push-module
        with:
          module-name: petstoreorderservice
          branch-name: ${{ github.ref_name }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstorepetservice
        if: ${{ inputs.project == 'petstorepetservice' || inputs.project == 'all' }}
        uses: ./.github/actions/build-and-push-module
        with:
          module-name: petstorepetservice
          branch-name: ${{ github.ref_name }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstoreproductservice
        if: ${{ inputs.project == 'petstoreproductservice' || inputs.project == 'all' }}
        uses: ./.github/actions/build-and-push-module
        with:
          module-name: petstoreproductservice
          branch-name: ${{ github.ref_name }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}
