name: Build and Deploy Selected Module

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Select the project to build and deploy'
        required: true
        type: choice
        options:
          - petstoreapp
          - petstoreorderservice
          - petstorepetservice
          - petstoreproductservice
          - orderitemsreserver
          - all

jobs:
  detect-and-build:
    name: Build and Deploy Selected Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Generate new tag
        id: generate_tag
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME:-${GITHUB_HEAD_REF}}
          BRANCH_NAME=${BRANCH_NAME//\//-}
          BUILD_NUMBER=$(printf "%04d" $GITHUB_RUN_NUMBER)
          TAG="${BRANCH_NAME}-${BUILD_NUMBER}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and Push petstoreapp
        if: ${{ inputs.project == 'petstoreapp' || inputs.project == 'all' }}
        uses: ./.github/actions/container-app-build-and-deploy
        with:
          module-name: petstoreapp
          container-name: 'ca-ps-petstoreapp'
          tag: ${{ steps.generate_tag.outputs.tag }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstoreorderservice
        if: ${{ inputs.project == 'petstoreorderservice' || inputs.project == 'all' }}
        uses: ./.github/actions/container-app-build-and-deploy
        with:
          module-name: petstoreorderservice
          container-name: 'ca-ps-petstoreorderservice'
          tag: ${{ steps.generate_tag.outputs.tag }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstorepetservice
        if: ${{ inputs.project == 'petstorepetservice' || inputs.project == 'all' }}
        uses: ./.github/actions/container-app-build-and-deploy
        with:
          module-name: petstorepetservice
          container-name: 'ca-ps-petstorepetservice'
          tag: ${{ steps.generate_tag.outputs.tag }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push petstoreproductservice
        if: ${{ inputs.project == 'petstoreproductservice' || inputs.project == 'all' }}
        uses: ./.github/actions/container-app-build-and-deploy
        with:
          module-name: petstoreproductservice
          container-name: 'ca-ps-petstoreproductservice'
          tag: ${{ steps.generate_tag.outputs.tag }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}

      - name: Build and Push orderitemsreserver
        if: ${{ inputs.project == 'orderitemsreserver' || inputs.project == 'all' }}
        uses: ./.github/actions/function-app-build-and-deploy
        with:
          module-name: orderitemsreserver
          function-name: ${{ vars.FUNCTION_APP_NAME }}
          tag: ${{ steps.generate_tag.outputs.tag }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          azure-acr-registry-name: ${{ vars.AZURE_ACR_REGISTRY_NAME }}
          azure-acr-registry-username: ${{ secrets.AZURE_ACR_REGISTRY_USERNAME }}
          azure-acr-registry-password: ${{ secrets.AZURE_ACR_REGISTRY_PASSWORD }}