spring:
  application:
    name: petstoreorderservice
  cloud:
    azure:
      cosmos:
        endpoint: ${COSMOSDB_ACCOUNT_ENDPOINT}
        key: ${COSMOSDB_PRIMARY_KEY}
        database: ${COSMOSDB_DATABASE_NAME}
        populate-query-metrics: true

server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false

logging:
  level:
    root: INFO
    com.chtrembl: DEBUG
